### ISSUE TITLE
How to build own apps?

### ISSUE THREAD

**Issue by ugintl** [BernStrom/YumMeals#21]
How can I build my own apps? What tools I would need?

**Comment by ugintl** [comment]
@farkadi06 Can you please tell me how to install it?

**Comment by BernStrom** [comment]
Hi @ugintl, there are many ways and various tools you can use to build an app. My project - YumMeals is simply one of the many ways. It wouldn't be possible for me to tell you exactly what you'll need, as I have no idea what your project is about and what are your requirements for your app.

If you're wanting to build an app as a personal project, the first thing you need to ask yourself is do you want your app to be supported across multi-platforms, or do you just want to build on one single platform.

For building cross-platform apps, the most common tools used are the React Native framework (created by Facebook) and the Flutter SDK (created by Google). For native, single-platform development, that would be SwiftUI/ UIKit (created by Apple) for Apple devices (iOS, macOS, watchOS, etc.) and Java/ Kotlin for Android devices.

I hope this helped give you a starting point on how to decide on what specific tools you need to build your own apps. 🙂
